integration:
  name: rspec
  arguments:
    - spec/models/user_spec.rb
    - spec/models/blog_spec.rb

jobs: 1

requires:
  - application
  - application_record
  - content_available
  - user
  - blog
includes:
  - config
  - app/models/
  - app/models/concerns/

matcher:
  subjects:
    - User
    - Blog

# environment_variables:
#   RAILS_ENV: test

usage: opensource
