services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Users/i.akihiro.nagai/work/tmp/mutant-test/mutation-testing-rails:cached
      #- ./container/bundle:/usr/local/bundle:cached
    depends_on:
      - db
    command: tail -f /dev/null
    environment:
      - DB_HOST=db
      - DB_PORT=3306

  db:
    restart: always
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=mutation_testing_rails_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./config/db/my.cnf:/etc/mysql/conf.d/custom.cnf
      - mutant-rails-mysql8-data:/var/lib/mysql
    ports:
      - "33306:3306"

volumes:
  mutant-rails-mysql8-data:
