services:
  db:
    restart: always
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=mutation_testing_rails_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./config/db/my.cnf:/etc/mysql/conf.d/custom.cnf
      - mutant-rails-mysql8-data:/var/lib/mysql
    ports:
      - "33306:3306"

volumes:
  mutant-rails-mysql8-data:
